# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Asana.Connection do
  @moduledoc """
  Builds and executes Req-based HTTP connections for Asana.
  """

  @type t :: Req.Request.t()

  @base_url "https://app.asana.com/api/1.0"
  @default_headers [{"user-agent", "elixir-asana"}]
  @scopes []

  @doc """
  Configure a connection using either a provided OAuth2 bearer token or a
  token fetcher callback.
  """
  @spec new(String.t() | (list(String.t()) -> String.t())) :: t()
  def new(token) when is_binary(token) do
    Req.new(
      base_url: @base_url,
      headers: @default_headers,
      auth: {:bearer, token}
    )
  end

  def new(token_fetcher) when is_function(token_fetcher, 1) do
    token_fetcher.(@scopes)
    |> new()
  end

  @doc """
  Configure a connection using basic auth credentials.
  """
  @spec new(String.t(), String.t()) :: t()
  def new(username, password) when is_binary(username) and is_binary(password) do
    basic = "Basic " <> Base.encode64("#{username}:#{password}")

    Req.new(
      base_url: @base_url,
      headers: [{"authorization", basic} | @default_headers]
    )
  end

  @doc """
  Configure an unauthenticated client connection.
  """
  @spec new() :: t()
  def new do
    Req.new(base_url: @base_url, headers: @default_headers)
  end

  @doc """
  Executes a request option list produced by `Asana.RequestBuilder`.
  """
  @spec request(t(), keyword()) :: {:ok, Req.Response.t()} | {:error, term()}
  def request(%Req.Request{} = connection, request_options) when is_list(request_options) do
    {method, request_options} = Keyword.pop(request_options, :method, :get)
    {url, request_options} = Keyword.pop(request_options, :url, "")
    {query, request_options} = Keyword.pop(request_options, :query, [])
    {headers, request_options} = Keyword.pop(request_options, :headers, [])
    {body, request_options} = Keyword.pop(request_options, :body)
    {form, request_options} = Keyword.pop(request_options, :form)
    {multipart, request_options} = Keyword.pop(request_options, :form_multipart)

    req_options =
      request_options
      |> Keyword.put(:method, method)
      |> Keyword.put(:url, url)
      |> maybe_put(:params, normalize_query_params(query))
      |> maybe_put(:headers, headers)
      |> maybe_put(:form, form)
      |> maybe_put_body(body, form, multipart)
      |> maybe_encode_multipart(multipart, form)

    Req.request(connection, req_options)
  end

  defp maybe_put(options, _key, nil), do: options
  defp maybe_put(options, _key, []), do: options
  defp maybe_put(options, key, value), do: Keyword.put(options, key, value)

  defp normalize_query_params(nil), do: nil
  defp normalize_query_params([]), do: []

  defp normalize_query_params(params) when is_list(params) do
    Enum.map(params, fn {key, value} -> {key, normalize_query_value(value)} end)
  end

  defp normalize_query_params(params) when is_map(params) do
    Map.new(params, fn {key, value} -> {key, normalize_query_value(value)} end)
  end

  defp normalize_query_params(params), do: params

  defp normalize_query_value(value) when is_list(value) do
    if List.ascii_printable?(value) do
      to_string(value)
    else
      Enum.map_join(value, ",", &normalize_query_item/1)
    end
  end

  defp normalize_query_value(value), do: value

  defp normalize_query_item(item) when is_map(item) or is_list(item), do: Poison.encode!(item)
  defp normalize_query_item(item), do: to_string(item)

  defp maybe_put_body(options, nil, _form, _multipart), do: options
  defp maybe_put_body(options, _body, form, _multipart) when not is_nil(form), do: options
  defp maybe_put_body(options, _body, _form, multipart) when not is_nil(multipart), do: options

  defp maybe_put_body(options, body, _form, _multipart) when is_binary(body),
    do: Keyword.put(options, :body, body)

  defp maybe_put_body(options, body, _form, _multipart), do: Keyword.put(options, :json, body)

  defp maybe_encode_multipart(options, nil, _form), do: options
  defp maybe_encode_multipart(options, [], _form), do: options

  defp maybe_encode_multipart(options, multipart, form) when is_list(multipart) do
    boundary = multipart_boundary()
    multipart = multipart ++ multipart_form_fields(form)
    body = encode_multipart_body(multipart, boundary)
    content_type = "multipart/form-data; boundary=" <> boundary

    options
    |> Keyword.delete(:form)
    |> Keyword.put(:body, body)
    |> Keyword.put(
      :headers,
      put_or_replace_header(Keyword.get(options, :headers, []), "content-type", content_type)
    )
  end

  defp multipart_form_fields(nil), do: []

  defp multipart_form_fields(form) when is_map(form) do
    Enum.map(form, fn {key, value} -> {to_string(key), encode_form_value(value)} end)
  end

  defp multipart_form_fields(form) when is_list(form) do
    Enum.map(form, fn {key, value} -> {to_string(key), encode_form_value(value)} end)
  end

  defp encode_form_value(value) when is_binary(value), do: value
  defp encode_form_value(value) when is_map(value) or is_list(value), do: Poison.encode!(value)
  defp encode_form_value(value), do: to_string(value)

  defp multipart_boundary do
    "----asana-#{Base.encode16(:crypto.strong_rand_bytes(12), case: :lower)}"
  end

  defp encode_multipart_body(parts, boundary) do
    [
      Enum.map(parts, &encode_multipart_part(&1, boundary)),
      "--",
      boundary,
      "--\r\n"
    ]
  end

  defp encode_multipart_part({name, {:file, path}}, boundary) do
    encode_multipart_part({name, {:file, path}, []}, boundary)
  end

  defp encode_multipart_part({name, {:file, path}, headers}, boundary) do
    filename = Path.basename(path)
    file_content = File.read!(path)

    headers =
      headers
      |> normalize_headers()
      |> put_new_header("content-type", "application/octet-stream")

    [
      "--",
      boundary,
      "\r\n",
      "content-disposition: form-data; name=\"",
      to_string(name),
      "\"; filename=\"",
      filename,
      "\"\r\n",
      encode_headers(headers),
      "\r\n",
      file_content,
      "\r\n"
    ]
  end

  defp encode_multipart_part({name, value}, boundary) do
    encode_multipart_part({name, value, []}, boundary)
  end

  defp encode_multipart_part({name, value, headers}, boundary) do
    [
      "--",
      boundary,
      "\r\n",
      "content-disposition: form-data; name=\"",
      to_string(name),
      "\"\r\n",
      encode_headers(normalize_headers(headers)),
      "\r\n",
      encode_form_value(value),
      "\r\n"
    ]
  end

  defp encode_headers([]), do: []

  defp encode_headers(headers) do
    Enum.map(headers, fn {name, value} ->
      [to_string(name), ": ", to_string(value), "\r\n"]
    end)
  end

  defp normalize_headers(headers) when is_list(headers) do
    Enum.map(headers, fn {name, value} -> {to_string(name), to_string(value)} end)
  end

  defp normalize_headers(_), do: []

  defp put_new_header(headers, name, value) do
    if Enum.any?(headers, fn {header_name, _} ->
         String.downcase(header_name) == String.downcase(name)
       end) do
      headers
    else
      [{name, value} | headers]
    end
  end

  defp put_or_replace_header(headers, name, value) do
    filtered =
      Enum.reject(headers, fn
        {header_name, _} -> String.downcase(to_string(header_name)) == String.downcase(name)
        _ -> false
      end)

    [{name, value} | filtered]
  end
end
