defmodule Asana.OperationClient do
  @moduledoc """
  Compatibility client for operation modules generated by `oapi_generator`.
  """

  @client_option_keys [:token, :base_url, :requester, :sleep_fn, :max_retries]

  @spec request(map()) :: {:ok, term()} | {:error, Asana.Error.t()}
  def request(request) when is_map(request) do
    op_opts = Map.get(request, :opts, [])
    client = Asana.Client.new(Keyword.take(op_opts, @client_option_keys))
    request_body = Map.get(request, :body)
    request_content = Map.get(request, :request)

    request_opts =
      []
      |> Keyword.put(:method, Map.fetch!(request, :method))
      |> Keyword.put(:url, Map.fetch!(request, :url))
      |> maybe_put_params(Map.get(request, :query))
      |> maybe_put_body(request_body, request_content)

    Asana.Client.request_full(client, request_opts)
  end

  defp maybe_put_params(opts, nil), do: opts

  defp maybe_put_params(opts, query) when is_list(query) do
    params =
      query
      |> Enum.reject(fn {_k, v} -> is_nil(v) end)
      |> Map.new()

    Keyword.put(opts, :params, params)
  end

  defp maybe_put_params(opts, query) when is_map(query) do
    params =
      query
      |> Enum.reject(fn {_k, v} -> is_nil(v) end)
      |> Map.new()

    Keyword.put(opts, :params, params)
  end

  defp maybe_put_body(opts, nil, _request_content), do: opts

  defp maybe_put_body(opts, body, request_content) do
    if multipart_request?(request_content) do
      case to_form_multipart(body) do
        nil -> Keyword.put(opts, :body, body)
        fields -> Keyword.put(opts, :form_multipart, fields)
      end
    else
      maybe_put_json_body(opts, body, request_content)
    end
  end

  defp maybe_put_json_body(opts, body, request_content) do
    if json_request?(request_content) and (is_map(body) or is_list(body)) do
      Keyword.put(opts, :json, body)
    else
      Keyword.put(opts, :body, body)
    end
  end

  defp multipart_request?(request_content) when is_list(request_content) do
    Enum.any?(request_content, fn
      {content_type, _schema} when is_binary(content_type) ->
        String.starts_with?(String.downcase(content_type), "multipart/form-data")

      _ ->
        false
    end)
  end

  defp multipart_request?(_), do: false

  defp json_request?(request_content) when is_list(request_content) do
    Enum.any?(request_content, fn
      {content_type, _schema} when is_binary(content_type) ->
        String.starts_with?(String.downcase(content_type), "application/json")

      _ ->
        false
    end)
  end

  defp json_request?(_), do: false

  defp to_form_multipart(body) when is_list(body) do
    body
    |> Enum.reject(fn {_k, v} -> is_nil(v) end)
  end

  defp to_form_multipart(%_{} = body) do
    body
    |> Map.from_struct()
    |> to_form_multipart()
  end

  defp to_form_multipart(body) when is_map(body) do
    body
    |> Enum.reject(fn {_k, v} -> is_nil(v) end)
  end

  defp to_form_multipart(_), do: nil
end
