# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Asana.RequestBuilder do
  @moduledoc """
  Helper functions for building Req requests.
  """

  @doc """
  Specify the request method when building a request.
  """
  @spec method(map(), atom()) :: map()
  def method(request, m), do: Map.put_new(request, :method, m)

  @doc """
  Specify the request URL when building a request.
  """
  @spec url(map(), String.t()) :: map()
  def url(request, u), do: Map.put_new(request, :url, u)

  @doc """
  Add optional parameters to the request.
  """
  @spec add_optional_params(map(), %{optional(atom()) => atom()}, keyword()) :: map()
  def add_optional_params(request, _, []), do: request

  def add_optional_params(request, definitions, [{key, value} | tail]) do
    case definitions do
      %{^key => location} ->
        request
        |> add_param(location, key, value)
        |> add_optional_params(definitions, tail)

      _ ->
        add_optional_params(request, definitions, tail)
    end
  end

  @doc """
  Add a parameter to a request.
  """
  @spec add_param(map(), atom(), atom(), any()) :: map()
  def add_param(request, :body, :body, value), do: Map.put(request, :body, value)

  def add_param(request, :body, key, value) do
    field = {to_string(key), Poison.encode!(value)}
    Map.update(request, :form_multipart, [field], &(&1 ++ [field]))
  end

  def add_param(request, :headers, key, value) do
    header = {to_string(key), to_string(value)}
    Map.update(request, :headers, [header], &(&1 ++ [header]))
  end

  def add_param(request, :file, name, path) do
    field = {name, {:file, path}}
    Map.update(request, :form_multipart, [field], &(&1 ++ [field]))
  end

  def add_param(request, :form, name, value) do
    Map.update(request, :form, %{name => value}, &Map.put(&1, name, value))
  end

  def add_param(request, location, key, value) do
    Map.update(request, location, [{key, value}], &(&1 ++ [{key, value}]))
  end

  @doc """
  Preserve compatibility with generated request pipelines that call `ensure_body/1`.
  """
  @spec ensure_body(map()) :: map()
  def ensure_body(%{body: nil} = request), do: %{request | body: ""}
  def ensure_body(request), do: Map.put_new(request, :body, "")

  @doc """
  Decode a Req response into the expected model struct.
  """
  @spec decode(Req.Response.t() | term(), false | struct() | [struct()]) ::
          {:ok, struct()} | {:ok, Req.Response.t()} | {:error, any()}
  def decode(%Req.Response{} = response, false), do: {:ok, response}
  def decode(%Req.Response{body: body}, struct), do: decode_body(body, struct)

  @spec evaluate_response({:ok, Req.Response.t()} | {:error, any()}, list()) ::
          {:ok, any()} | {:error, any()}
  def evaluate_response({:ok, %Req.Response{} = response}, mapping) do
    resolve_mapping(response, mapping)
  end

  def evaluate_response({:error, _} = error, _), do: error

  @spec resolve_mapping(Req.Response.t(), list(), any()) :: {:ok, any()} | {:error, any()}
  def resolve_mapping(response, mapping, default \\ nil)

  def resolve_mapping(
        %Req.Response{status: status} = response,
        [{mapping_status, struct} | _],
        _
      )
      when is_integer(mapping_status) and status == mapping_status do
    decode(response, struct)
  end

  def resolve_mapping(
        %Req.Response{status: status} = response,
        [{"5XX", struct} | _],
        _
      )
      when status >= 500 and status <= 599 do
    decode(response, struct)
  end

  def resolve_mapping(response, [{:default, struct} | tail], _),
    do: resolve_mapping(response, tail, struct)

  def resolve_mapping(response, [_ | tail], struct), do: resolve_mapping(response, tail, struct)
  def resolve_mapping(response, [], nil), do: {:error, response}
  def resolve_mapping(response, [], struct), do: decode(response, struct)

  defp decode_body(body, struct) when is_binary(body), do: Poison.decode(body, as: struct)

  defp decode_body(body, struct) when is_map(body) or is_list(body) do
    body
    |> Poison.encode!()
    |> Poison.decode(as: struct)
  end

  defp decode_body(body, _struct), do: {:error, {:unexpected_response_body, body}}
end
