defmodule Asana.Task.Request do
  @moduledoc """
  Provides struct and type for a Task.Request
  """
  use Asana.Encoder

  @type t :: %__MODULE__{
          __info__: map,
          actual_time_minutes: number | nil,
          approval_status: String.t() | nil,
          assigned_by: Asana.Task.RequestAssignedBy.t() | nil,
          assignee: String.t() | nil,
          assignee_section: String.t() | nil,
          assignee_status: String.t() | nil,
          completed: boolean | nil,
          completed_at: DateTime.t() | nil,
          completed_by: Asana.Task.RequestCompletedBy.t() | nil,
          created_at: DateTime.t() | nil,
          created_by: Asana.Task.RequestCreatedBy.t() | nil,
          custom_fields: map | nil,
          custom_type: String.t() | nil,
          custom_type_status_option: String.t() | nil,
          dependencies: [Asana.AsanaResource.t()] | nil,
          dependents: [Asana.AsanaResource.t()] | nil,
          due_at: DateTime.t() | nil,
          due_on: Date.t() | nil,
          external: Asana.Task.RequestExternal.t() | nil,
          followers: [String.t()] | nil,
          gid: String.t() | nil,
          hearted: boolean | nil,
          hearts: [Asana.Like.t()] | nil,
          html_notes: String.t() | nil,
          is_rendered_as_separator: boolean | nil,
          liked: boolean | nil,
          likes: [Asana.Like.t()] | nil,
          memberships: [Asana.Task.RequestMemberships.t()] | nil,
          modified_at: DateTime.t() | nil,
          name: String.t() | nil,
          notes: String.t() | nil,
          num_hearts: integer | nil,
          num_likes: integer | nil,
          num_subtasks: integer | nil,
          parent: String.t() | nil,
          projects: [String.t()] | nil,
          resource_subtype: String.t() | nil,
          resource_type: String.t() | nil,
          start_at: DateTime.t() | nil,
          start_on: Date.t() | nil,
          tags: [String.t()] | nil,
          workspace: String.t() | nil
        }

  defstruct [
    :__info__,
    :actual_time_minutes,
    :approval_status,
    :assigned_by,
    :assignee,
    :assignee_section,
    :assignee_status,
    :completed,
    :completed_at,
    :completed_by,
    :created_at,
    :created_by,
    :custom_fields,
    :custom_type,
    :custom_type_status_option,
    :dependencies,
    :dependents,
    :due_at,
    :due_on,
    :external,
    :followers,
    :gid,
    :hearted,
    :hearts,
    :html_notes,
    :is_rendered_as_separator,
    :liked,
    :likes,
    :memberships,
    :modified_at,
    :name,
    :notes,
    :num_hearts,
    :num_likes,
    :num_subtasks,
    :parent,
    :projects,
    :resource_subtype,
    :resource_type,
    :start_at,
    :start_on,
    :tags,
    :workspace
  ]

  @doc false
  @spec __fields__(atom) :: keyword
  def __fields__(type \\ :t)

  def __fields__(:t) do
    [
      actual_time_minutes: :number,
      approval_status: {:enum, ["pending", "approved", "rejected", "changes_requested"]},
      assigned_by: {Asana.Task.RequestAssignedBy, :t},
      assignee: :string,
      assignee_section: :string,
      assignee_status: {:enum, ["today", "upcoming", "later", "new", "inbox"]},
      completed: :boolean,
      completed_at: {:string, "date-time"},
      completed_by: {Asana.Task.RequestCompletedBy, :t},
      created_at: {:string, "date-time"},
      created_by: {Asana.Task.RequestCreatedBy, :t},
      custom_fields: :map,
      custom_type: :string,
      custom_type_status_option: :string,
      dependencies: [{Asana.AsanaResource, :t}],
      dependents: [{Asana.AsanaResource, :t}],
      due_at: {:string, "date-time"},
      due_on: {:string, "date"},
      external: {Asana.Task.RequestExternal, :t},
      followers: [:string],
      gid: :string,
      hearted: :boolean,
      hearts: [{Asana.Like, :t}],
      html_notes: :string,
      is_rendered_as_separator: :boolean,
      liked: :boolean,
      likes: [{Asana.Like, :t}],
      memberships: [{Asana.Task.RequestMemberships, :t}],
      modified_at: {:string, "date-time"},
      name: :string,
      notes: :string,
      num_hearts: :integer,
      num_likes: :integer,
      num_subtasks: :integer,
      parent: :string,
      projects: [:string],
      resource_subtype: {:enum, ["default_task", "milestone", "approval", "custom"]},
      resource_type: :string,
      start_at: {:string, "date-time"},
      start_on: {:string, "date"},
      tags: [:string],
      workspace: :string
    ]
  end
end
