defmodule Asana.Project.Request do
  @moduledoc """
  Provides struct and type for a Project.Request
  """
  use Asana.Encoder

  @type t :: %__MODULE__{
          __info__: map,
          archived: boolean | nil,
          color: String.t() | nil,
          created_at: DateTime.t() | nil,
          current_status: Asana.Project.RequestCurrentStatus.t() | nil,
          current_status_update: Asana.Project.RequestCurrentStatusUpdate.t() | nil,
          custom_field_settings: [Asana.CustomField.Setting.response()] | nil,
          custom_fields: map | nil,
          default_access_level: String.t() | nil,
          default_view: String.t() | nil,
          due_date: Date.t() | nil,
          due_on: Date.t() | nil,
          followers: String.t() | nil,
          gid: String.t() | nil,
          html_notes: String.t() | nil,
          icon: String.t() | nil,
          members: [Asana.User.compact()] | nil,
          minimum_access_level_for_customization: String.t() | nil,
          minimum_access_level_for_sharing: String.t() | nil,
          modified_at: DateTime.t() | nil,
          name: String.t() | nil,
          notes: String.t() | nil,
          owner: String.t() | nil,
          privacy_setting: String.t() | nil,
          public: boolean | nil,
          resource_type: String.t() | nil,
          start_on: Date.t() | nil,
          team: String.t() | nil,
          workspace: String.t() | nil
        }

  defstruct [
    :__info__,
    :archived,
    :color,
    :created_at,
    :current_status,
    :current_status_update,
    :custom_field_settings,
    :custom_fields,
    :default_access_level,
    :default_view,
    :due_date,
    :due_on,
    :followers,
    :gid,
    :html_notes,
    :icon,
    :members,
    :minimum_access_level_for_customization,
    :minimum_access_level_for_sharing,
    :modified_at,
    :name,
    :notes,
    :owner,
    :privacy_setting,
    :public,
    :resource_type,
    :start_on,
    :team,
    :workspace
  ]

  @doc false
  @spec __fields__(atom) :: keyword
  def __fields__(type \\ :t)

  def __fields__(:t) do
    [
      archived: :boolean,
      color:
        {:enum,
         [
           "dark-pink",
           "dark-green",
           "dark-blue",
           "dark-red",
           "dark-teal",
           "dark-brown",
           "dark-orange",
           "dark-purple",
           "dark-warm-gray",
           "light-pink",
           "light-green",
           "light-blue",
           "light-red",
           "light-teal",
           "light-brown",
           "light-orange",
           "light-purple",
           "light-warm-gray",
           "none",
           nil
         ]},
      created_at: {:string, "date-time"},
      current_status: {Asana.Project.RequestCurrentStatus, :t},
      current_status_update: {Asana.Project.RequestCurrentStatusUpdate, :t},
      custom_field_settings: [{Asana.CustomField.Setting, :response}],
      custom_fields: :map,
      default_access_level: {:enum, ["admin", "editor", "commenter", "viewer"]},
      default_view: {:enum, ["list", "board", "calendar", "timeline"]},
      due_date: {:string, "date"},
      due_on: {:string, "date"},
      followers: :string,
      gid: :string,
      html_notes: :string,
      icon:
        {:enum,
         [
           "list",
           "board",
           "timeline",
           "calendar",
           "rocket",
           "people",
           "graph",
           "star",
           "bug",
           "light_bulb",
           "globe",
           "gear",
           "notebook",
           "computer",
           "check",
           "target",
           "html",
           "megaphone",
           "chat_bubbles",
           "briefcase",
           "page_layout",
           "mountain_flag",
           "puzzle",
           "presentation",
           "line_and_symbols",
           "speed_dial",
           "ribbon",
           "shoe",
           "shopping_basket",
           "map",
           "ticket",
           "coins"
         ]},
      members: [{Asana.User, :compact}],
      minimum_access_level_for_customization: {:enum, ["admin", "editor"]},
      minimum_access_level_for_sharing: {:enum, ["admin", "editor"]},
      modified_at: {:string, "date-time"},
      name: :string,
      notes: :string,
      owner: :string,
      privacy_setting: {:enum, ["public_to_workspace", "private_to_team", "private"]},
      public: :boolean,
      resource_type: :string,
      start_on: {:string, "date"},
      team: :string,
      workspace: :string
    ]
  end
end
