# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Asana.Model.BatchData do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"actions"
  ]

  @type t :: %__MODULE__{
    :"actions" => [Asana.Model.BatchRequest.t] | nil
  }
end

defimpl Poison.Decoder, for: Asana.Model.BatchData do
  import Asana.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"actions", :list, Asana.Model.BatchRequest, options)
  end
end

