# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Asana.Model.ProjectsData do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"name",
    :"notes",
    :"workspace",
    :"team"
  ]

  @type t :: %__MODULE__{
    :"name" => String.t | nil,
    :"notes" => String.t | nil,
    :"workspace" => integer() | nil,
    :"team" => integer() | nil
  }
end

defimpl Poison.Decoder, for: Asana.Model.ProjectsData do
  def decode(value, _options) do
    value
  end
end

