# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Asana.Model.TasksTaskGidAddFollowersData do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"followers"
  ]

  @type t :: %__MODULE__{
    :"followers" => [integer()]
  }
end

defimpl Poison.Decoder, for: Asana.Model.TasksTaskGidAddFollowersData do
  def decode(value, _options) do
    value
  end
end

