# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Asana.Model.AsanaCreatedByAndAt do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"created_by",
    :"created_at"
  ]

  @type t :: %__MODULE__{
    :"created_by" => User | nil,
    :"created_at" => DateTime.t | nil
  }
end

defimpl Poison.Decoder, for: Asana.Model.AsanaCreatedByAndAt do
  import Asana.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"created_by", :struct, Asana.Model.User, options)
  end
end

