# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Asana.Model.AsanaCreatedAt do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"created_at"
  ]

  @type t :: %__MODULE__{
    :"created_at" => DateTime.t | nil
  }
end

defimpl Poison.Decoder, for: Asana.Model.AsanaCreatedAt do
  def decode(value, _options) do
    value
  end
end

