# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Asana.Model.Attachment do
  @moduledoc """
  An *attachment* object represents any file attached to a task in Asana, whether it’s an uploaded file or one associated via a third-party service such as Dropbox or Google Drive.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"download_url",
    :"host",
    :"name",
    :"parent",
    :"view_url",
    :"id",
    :"gid",
    :"resource_type",
    :"created_at"
  ]

  @type t :: %__MODULE__{
    :"download_url" => String.t | nil,
    :"host" => String.t | nil,
    :"name" => String.t | nil,
    :"parent" => TaskCompact | nil,
    :"view_url" => String.t | nil,
    :"id" => integer() | nil,
    :"gid" => integer() | nil,
    :"resource_type" => String.t | nil,
    :"created_at" => DateTime.t | nil
  }
end

defimpl Poison.Decoder, for: Asana.Model.Attachment do
  import Asana.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"parent", :struct, Asana.Model.TaskCompact, options)
  end
end

