# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Asana.Model.BatchResponse do
  @moduledoc """
  A response object returned from a batch request.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"status_code",
    :"headers",
    :"body"
  ]

  @type t :: %__MODULE__{
    :"status_code" => integer() | nil,
    :"headers" => map() | nil,
    :"body" => map() | nil
  }
end

defimpl Poison.Decoder, for: Asana.Model.BatchResponse do
  def decode(value, _options) do
    value
  end
end

