# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Asana.Model.BatchRequestOptions do
  @moduledoc """
  Pagination (`limit` and `offset`) and output options (`fields` or `expand`) for the action. “Pretty” JSON output is not an available option on individual actions; if you want pretty output, specify that option on the parent request.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"limit",
    :"offset",
    :"fields",
    :"expand"
  ]

  @type t :: %__MODULE__{
    :"limit" => integer() | nil,
    :"offset" => integer() | nil,
    :"fields" => [String.t] | nil,
    :"expand" => String.t | nil
  }
end

defimpl Poison.Decoder, for: Asana.Model.BatchRequestOptions do
  def decode(value, _options) do
    value
  end
end

