# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Asana.Model.CustomField do
  @moduledoc """
  Custom Fields store the metadata that is used in order to add user-specified information to tasks in Asana. Be sure to reference the [Custom Fields] (https://asana.com/developers/documentation/getting-started/custom-fields) developer documentation for more information about how custom fields relate to various resources in Asana.  Users in Asana can [lock custom fields] (https://asana.com/guide/help/premium/custom-fields#gl-lock-fields), which will make them read-only when accessed by other users. Attempting to edit a locked custom field will return HTTP error code `403 Forbidden`.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"description",
    :"type",
    :"enum_options",
    :"precision",
    :"id",
    :"gid",
    :"resource_type",
    :"resource_subtype"
  ]

  @type t :: %__MODULE__{
    :"description" => String.t | nil,
    :"type" => String.t | nil,
    :"enum_options" => [Asana.Model.EnumOption.t] | nil,
    :"precision" => integer() | nil,
    :"id" => integer() | nil,
    :"gid" => integer() | nil,
    :"resource_type" => String.t | nil,
    :"resource_subtype" => String.t | nil
  }
end

defimpl Poison.Decoder, for: Asana.Model.CustomField do
  import Asana.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"enum_options", :list, Asana.Model.EnumOption, options)
  end
end

