# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Asana.Model.EmptyObject do
  @moduledoc """
  An empty object.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"data"
  ]

  @type t :: %__MODULE__{
    :"data" => map() | nil
  }
end

defimpl Poison.Decoder, for: Asana.Model.EmptyObject do
  def decode(value, _options) do
    value
  end
end

