# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Asana.Model.ErrorErrors do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"message",
    :"phrase"
  ]

  @type t :: %__MODULE__{
    :"message" => String.t | nil,
    :"phrase" => String.t | nil
  }
end

defimpl Poison.Decoder, for: Asana.Model.ErrorErrors do
  def decode(value, _options) do
    value
  end
end

