# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Asana.Model.EventResource do
  @moduledoc """
  The resource the event occurred on.  **Note**: The resource that triggered the event may be different from the one that the events were requested for. For example, a subscription to a project will contain events for tasks contained within the project.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"id",
    :"name"
  ]

  @type t :: %__MODULE__{
    :"id" => integer() | nil,
    :"name" => String.t | nil
  }
end

defimpl Poison.Decoder, for: Asana.Model.EventResource do
  def decode(value, _options) do
    value
  end
end

