# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Asana.Model.InlineObject18 do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"resource",
    :"target"
  ]

  @type t :: %__MODULE__{
    :"resource" => integer(),
    :"target" => String.t
  }
end

defimpl Poison.Decoder, for: Asana.Model.InlineObject18 do
  def decode(value, _options) do
    value
  end
end

