# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Asana.Model.InlineObject9 do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"project",
    :"section",
    :"before_section",
    :"after_section"
  ]

  @type t :: %__MODULE__{
    :"project" => integer(),
    :"section" => integer(),
    :"before_section" => integer(),
    :"after_section" => integer()
  }
end

defimpl Poison.Decoder, for: Asana.Model.InlineObject9 do
  def decode(value, _options) do
    value
  end
end

