# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Asana.Model.InlineObject5 do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"organization"
  ]

  @type t :: %__MODULE__{
    :"organization" => integer() | nil
  }
end

defimpl Poison.Decoder, for: Asana.Model.InlineObject5 do
  def decode(value, _options) do
    value
  end
end

