# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Asana.Model.InlineObject10 do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"task",
    :"text"
  ]

  @type t :: %__MODULE__{
    :"task" => integer(),
    :"text" => String.t
  }
end

defimpl Poison.Decoder, for: Asana.Model.InlineObject10 do
  def decode(value, _options) do
    value
  end
end

