# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Asana.Model.InlineObject6 do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"project",
    :"text",
    :"color"
  ]

  @type t :: %__MODULE__{
    :"project" => integer(),
    :"text" => String.t,
    :"color" => String.t
  }
end

defimpl Poison.Decoder, for: Asana.Model.InlineObject6 do
  def decode(value, _options) do
    value
  end
end

