# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Asana.Model.OrganizationExport do
  @moduledoc """
  An *organization_export* object represents a request to export the complete data of an Organization in JSON format.  To export an Organization using this API:  * Create an `organization_export`   [request](https://asana.com/developers/api-reference/organization_exports#create)   and store the id that is returned. * Request the `organization_export` every few minutes, until the `state`   field contains ‘finished’. * Download the file located at the URL in the `download_url` field. * Exports can take a long time, from several minutes to a few hours for   large Organizations.  **Note**: These endpoints are only available to [Service Accounts](https://asana.com/guide/help/premium/service-accounts) of an [Enterprise](https://asana.com/enterprise) Organization.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"download_url",
    :"state",
    :"organization",
    :"id",
    :"gid",
    :"resource_type",
    :"created_at"
  ]

  @type t :: %__MODULE__{
    :"download_url" => String.t | nil,
    :"state" => String.t | nil,
    :"organization" => map() | nil,
    :"id" => integer() | nil,
    :"gid" => integer() | nil,
    :"resource_type" => String.t | nil,
    :"created_at" => DateTime.t | nil
  }
end

defimpl Poison.Decoder, for: Asana.Model.OrganizationExport do
  def decode(value, _options) do
    value
  end
end

