# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Asana.Model.Portfolio do
  @moduledoc """
  A *portfolio* gives a high-level overview of the status of multiple initiatives in Asana. Portfolios provide a dashboard overview of the state of multiple projects, including a progress report and the most recent [project status](https://asana.com/developers/api-reference/project_statuses) update.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"color",
    :"custom_field_settings",
    :"owner",
    :"workspace",
    :"id",
    :"gid",
    :"resource_type",
    :"created_at"
  ]

  @type t :: %__MODULE__{
    :"color" => String.t | nil,
    :"custom_field_settings" => [Asana.Model.CustomFieldSettings.t] | nil,
    :"owner" => UserCompact | nil,
    :"workspace" => WorkspaceCompact | nil,
    :"id" => integer() | nil,
    :"gid" => integer() | nil,
    :"resource_type" => String.t | nil,
    :"created_at" => DateTime.t | nil
  }
end

defimpl Poison.Decoder, for: Asana.Model.Portfolio do
  import Asana.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"custom_field_settings", :list, Asana.Model.CustomFieldSettings, options)
    |> deserialize(:"owner", :struct, Asana.Model.UserCompact, options)
    |> deserialize(:"workspace", :struct, Asana.Model.WorkspaceCompact, options)
  end
end

