# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Asana.Model.Project do
  @moduledoc """
  A *project* represents a prioritized list of tasks in Asana or a board with columns of tasks represented as cards. It exists in a single workspace or organization and is accessible to a subset of users in that workspace or organization, depending on its permissions.  Projects in organizations are shared with a single team. You cannot currently change the team of a project via the API. Non-organization workspaces do not have teams and so you should not specify the team of project in a regular workspace.  Followers of a project are a subset of the members of that project. Followers of a project will receive all updates including tasks created, added and removed from that project. Members of the project have access to and will receive status updates of the project. Adding followers to a project will add them as members if they are not already, removing followers from a project will not affect membership.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"name",
    :"archived",
    :"color",
    :"current_status",
    :"custom_field_settings",
    :"due_date",
    :"followers",
    :"html_notes",
    :"layout",
    :"members",
    :"modified_at",
    :"notes",
    :"owner",
    :"public",
    :"start_on",
    :"team",
    :"workspace",
    :"id",
    :"gid",
    :"resource_type",
    :"created_at"
  ]

  @type t :: %__MODULE__{
    :"name" => String.t | nil,
    :"archived" => boolean() | nil,
    :"color" => String.t | nil,
    :"current_status" => map() | nil,
    :"custom_field_settings" => [Asana.Model.CustomFieldSettings.t] | nil,
    :"due_date" => DateTime.t | nil,
    :"followers" => [Asana.Model.User.t] | nil,
    :"html_notes" => String.t | nil,
    :"layout" => String.t | nil,
    :"members" => [Asana.Model.User.t] | nil,
    :"modified_at" => DateTime.t | nil,
    :"notes" => String.t | nil,
    :"owner" => UserCompact | nil,
    :"public" => boolean() | nil,
    :"start_on" => Date.t | nil,
    :"team" => TeamCompact | nil,
    :"workspace" => WorkspaceCompact | nil,
    :"id" => integer() | nil,
    :"gid" => integer() | nil,
    :"resource_type" => String.t | nil,
    :"created_at" => DateTime.t | nil
  }
end

defimpl Poison.Decoder, for: Asana.Model.Project do
  import Asana.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"custom_field_settings", :list, Asana.Model.CustomFieldSettings, options)
    |> deserialize(:"followers", :list, Asana.Model.User, options)
    |> deserialize(:"members", :list, Asana.Model.User, options)
    |> deserialize(:"owner", :struct, Asana.Model.UserCompact, options)
    |> deserialize(:"start_on", :date, nil, options)
    |> deserialize(:"team", :struct, Asana.Model.TeamCompact, options)
    |> deserialize(:"workspace", :struct, Asana.Model.WorkspaceCompact, options)
  end
end

