# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Asana.Model.ProjectMembership do
  @moduledoc """
  With the introduction of “comment-only” projects in Asana, a user’s membership in a project comes with associated permissions. These permissions (whether a user has full access to the project or comment-only access) are accessible through the project memberships endpoints described here.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"user",
    :"project",
    :"write_access",
    :"id",
    :"gid",
    :"resource_type"
  ]

  @type t :: %__MODULE__{
    :"user" => Asana.Model.UserCompact.t | nil,
    :"project" => Asana.Model.ProjectCompact.t | nil,
    :"write_access" => String.t | nil,
    :"id" => integer() | nil,
    :"gid" => integer() | nil,
    :"resource_type" => String.t | nil
  }
end

defimpl Poison.Decoder, for: Asana.Model.ProjectMembership do
  import Asana.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"user", :struct, Asana.Model.UserCompact, options)
    |> deserialize(:"project", :struct, Asana.Model.ProjectCompact, options)
  end
end

