# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Asana.Model.Section do
  @moduledoc """
  A *section* is a subdivision of a project that groups tasks together. It can either be a header above a list of tasks in a list view or a column in a board view of a project.  Sections are largely a shared idiom in Asana’s API for both list and board views of a project regardless of the project’s layout.  The ‘memberships’ property when [getting a task](https://asana.com/developers/api-reference/tasks#get) will return the information for the section or the column under ‘section’ in the response.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"name",
    :"project",
    :"id",
    :"gid",
    :"resource_type",
    :"created_at"
  ]

  @type t :: %__MODULE__{
    :"name" => String.t | nil,
    :"project" => ProjectCompact | nil,
    :"id" => integer() | nil,
    :"gid" => integer() | nil,
    :"resource_type" => String.t | nil,
    :"created_at" => DateTime.t | nil
  }
end

defimpl Poison.Decoder, for: Asana.Model.Section do
  import Asana.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"project", :struct, Asana.Model.ProjectCompact, options)
  end
end

