# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Asana.Model.Team do
  @moduledoc """
  A *team* is used to group related projects and people together within an organization. Each project in an organization is associated with a team.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"description",
    :"html_description",
    :"id",
    :"gid",
    :"resource_type"
  ]

  @type t :: %__MODULE__{
    :"description" => String.t | nil,
    :"html_description" => String.t | nil,
    :"id" => integer() | nil,
    :"gid" => integer() | nil,
    :"resource_type" => String.t | nil
  }
end

defimpl Poison.Decoder, for: Asana.Model.Team do
  def decode(value, _options) do
    value
  end
end

