# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Asana.Model.UserIdObjectData do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"user"
  ]

  @type t :: %__MODULE__{
    :"user" => OneOfintegerstringstring | nil
  }
end

defimpl Poison.Decoder, for: Asana.Model.UserIdObjectData do
  import Asana.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"user", :struct, Asana.Model.OneOfintegerstringstring, options)
  end
end

