# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Asana.Model.UserTaskList do
  @moduledoc """
  A user task list represents the tasks assigned to a particular user. It provides API access to a user’s “My Tasks” view in Asana. A user’s “My Tasks” represent all of the tasks assigned to that user. It is visually divided into regions based on the task’s [`assignee_status`] (https://asana.com/developers/api-reference/tasks#field-assignee_status) for Asana users to triage their tasks based on when they can address them. When building an integration it’s worth noting that tasks with due dates will automatically move through `assignee_status` states as their due dates approach; read up on [task auto-promotion](https://asana.com/guide/help/fundamentals/my-tasks#gl-auto-promote) for more information.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"owner",
    :"workspace",
    :"id",
    :"gid",
    :"resource_type"
  ]

  @type t :: %__MODULE__{
    :"owner" => UserCompact | nil,
    :"workspace" => WorkspaceCompact | nil,
    :"id" => integer() | nil,
    :"gid" => integer() | nil,
    :"resource_type" => String.t | nil
  }
end

defimpl Poison.Decoder, for: Asana.Model.UserTaskList do
  import Asana.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"owner", :struct, Asana.Model.UserCompact, options)
    |> deserialize(:"workspace", :struct, Asana.Model.WorkspaceCompact, options)
  end
end

