# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Asana.Model.User do
  @moduledoc """
  A *user* object represents an account in Asana that can be given access to various workspaces, projects, and tasks.  Like other objects in the system, users are referred to by numerical IDs. However, the special string identifier `me` can be used anywhere a user ID is accepted, to refer to the current authenticated user.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"email",
    :"name",
    :"photo",
    :"workspaces",
    :"id",
    :"gid",
    :"resource_type"
  ]

  @type t :: %__MODULE__{
    :"email" => String.t | nil,
    :"name" => String.t | nil,
    :"photo" => map() | nil,
    :"workspaces" => [Asana.Model.Workspace.t] | nil,
    :"id" => integer() | nil,
    :"gid" => integer() | nil,
    :"resource_type" => String.t | nil
  }
end

defimpl Poison.Decoder, for: Asana.Model.User do
  import Asana.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"workspaces", :list, Asana.Model.Workspace, options)
  end
end

