# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Asana.Model.Webhook do
  @moduledoc """
  Webhooks allow an application to be notified of changes. This is in addition to the ability to fetch those changes directly as Events - in fact, Webhooks are just a way to receive [Events](https://asana.com/developers/api-reference/events) via HTTP POST at the time they occur instead of polling for them. For services accessible via HTTP this is often vastly more convenient, and if events are not too frequent can be significantly more efficient.  In both cases, however, changes are represented as Event objects - refer to the [Events documentation](https://asana.com/developers/api-reference/events) for more information on what data these events contain.  **Note**: While Webhooks send arrays of Event objects to their target, the Event objects themselves contain *only IDs*, rather than the actual resource they are referencing. Webhooks themselves contain only the information necessary to deliver the events to the desired target as they are generated.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"active",
    :"last_failure_at",
    :"last_failure_content",
    :"last_success_at",
    :"resource",
    :"target",
    :"id",
    :"gid",
    :"resource_type",
    :"created_at"
  ]

  @type t :: %__MODULE__{
    :"active" => boolean() | nil,
    :"last_failure_at" => DateTime.t | nil,
    :"last_failure_content" => String.t | nil,
    :"last_success_at" => DateTime.t | nil,
    :"resource" => AsanaNamedObject | nil,
    :"target" => String.t | nil,
    :"id" => integer() | nil,
    :"gid" => integer() | nil,
    :"resource_type" => String.t | nil,
    :"created_at" => DateTime.t | nil
  }
end

defimpl Poison.Decoder, for: Asana.Model.Webhook do
  import Asana.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"resource", :struct, Asana.Model.AsanaNamedObject, options)
  end
end

