# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Asana.Model.Workspace do
  @moduledoc """
  A *workspace* is the highest-level organizational unit in Asana. All projects and tasks have an associated workspace.  An *organization* is a special kind of workspace that represents a company. In an organization, you can group your projects into teams. You can read more about how organizations work on the Asana Guide. To tell if your workspace is an organization or not, check its `is_organization` property.  Over time, we intend to migrate most workspaces into organizations and to release more organization-specific functionality. We may eventually deprecate using workspace-based APIs for organizations. Currently, and until after some reasonable grace period following any further announcements, you can still reference organizations in any `workspace` parameter.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"email_domains",
    :"is_organization",
    :"id",
    :"gid",
    :"resource_type"
  ]

  @type t :: %__MODULE__{
    :"email_domains" => [String.t] | nil,
    :"is_organization" => boolean() | nil,
    :"id" => integer() | nil,
    :"gid" => integer() | nil,
    :"resource_type" => String.t | nil
  }
end

defimpl Poison.Decoder, for: Asana.Model.Workspace do
  def decode(value, _options) do
    value
  end
end

