defmodule Asana.Project do
  @moduledoc """
  Provides struct and types for a Project
  """
  use Asana.Encoder

  @type compact :: %__MODULE__{
          __info__: map,
          gid: String.t() | nil,
          name: String.t() | nil,
          resource_type: String.t() | nil
        }

  @type response :: %__MODULE__{
          __info__: map,
          archived: boolean | nil,
          color: String.t() | nil,
          completed: boolean | nil,
          completed_at: DateTime.t() | nil,
          completed_by: Asana.Project.CompletedBy.response() | nil,
          created_at: DateTime.t() | nil,
          created_from_template: Asana.Project.CreatedFromTemplate.response() | nil,
          current_status: Asana.Project.CurrentStatus.response() | nil,
          current_status_update: Asana.Project.CurrentStatusUpdate.response() | nil,
          custom_field_settings: [Asana.CustomField.Setting.response()] | nil,
          custom_fields: [Asana.CustomField.compact()] | nil,
          default_access_level: String.t() | nil,
          default_view: String.t() | nil,
          due_date: Date.t() | nil,
          due_on: Date.t() | nil,
          followers: [Asana.User.compact()] | nil,
          gid: String.t() | nil,
          html_notes: String.t() | nil,
          icon: String.t() | nil,
          members: [Asana.User.compact()] | nil,
          minimum_access_level_for_customization: String.t() | nil,
          minimum_access_level_for_sharing: String.t() | nil,
          modified_at: DateTime.t() | nil,
          name: String.t() | nil,
          notes: String.t() | nil,
          owner: Asana.Project.Owner.response() | nil,
          permalink_url: String.t() | nil,
          privacy_setting: String.t() | nil,
          project_brief: Asana.Project.ProjectBrief.response() | nil,
          public: boolean | nil,
          resource_type: String.t() | nil,
          start_on: Date.t() | nil,
          team: Asana.Project.Team.response() | nil,
          workspace: Asana.Project.Workspace.response() | nil
        }

  defstruct [
    :__info__,
    :archived,
    :color,
    :completed,
    :completed_at,
    :completed_by,
    :created_at,
    :created_from_template,
    :current_status,
    :current_status_update,
    :custom_field_settings,
    :custom_fields,
    :default_access_level,
    :default_view,
    :due_date,
    :due_on,
    :followers,
    :gid,
    :html_notes,
    :icon,
    :members,
    :minimum_access_level_for_customization,
    :minimum_access_level_for_sharing,
    :modified_at,
    :name,
    :notes,
    :owner,
    :permalink_url,
    :privacy_setting,
    :project_brief,
    :public,
    :resource_type,
    :start_on,
    :team,
    :workspace
  ]

  @doc false
  @spec __fields__(atom) :: keyword
  def __fields__(:compact) do
    [gid: :string, name: :string, resource_type: :string]
  end

  def __fields__(:response) do
    [
      archived: :boolean,
      color:
        {:enum,
         [
           "dark-pink",
           "dark-green",
           "dark-blue",
           "dark-red",
           "dark-teal",
           "dark-brown",
           "dark-orange",
           "dark-purple",
           "dark-warm-gray",
           "light-pink",
           "light-green",
           "light-blue",
           "light-red",
           "light-teal",
           "light-brown",
           "light-orange",
           "light-purple",
           "light-warm-gray",
           "none",
           nil
         ]},
      completed: :boolean,
      completed_at: {:string, "date-time"},
      completed_by: {Asana.Project.CompletedBy, :response},
      created_at: {:string, "date-time"},
      created_from_template: {Asana.Project.CreatedFromTemplate, :response},
      current_status: {Asana.Project.CurrentStatus, :response},
      current_status_update: {Asana.Project.CurrentStatusUpdate, :response},
      custom_field_settings: [{Asana.CustomField.Setting, :response}],
      custom_fields: [{Asana.CustomField, :compact}],
      default_access_level: {:enum, ["admin", "editor", "commenter", "viewer"]},
      default_view: {:enum, ["list", "board", "calendar", "timeline"]},
      due_date: {:string, "date"},
      due_on: {:string, "date"},
      followers: [{Asana.User, :compact}],
      gid: :string,
      html_notes: :string,
      icon:
        {:enum,
         [
           "list",
           "board",
           "timeline",
           "calendar",
           "rocket",
           "people",
           "graph",
           "star",
           "bug",
           "light_bulb",
           "globe",
           "gear",
           "notebook",
           "computer",
           "check",
           "target",
           "html",
           "megaphone",
           "chat_bubbles",
           "briefcase",
           "page_layout",
           "mountain_flag",
           "puzzle",
           "presentation",
           "line_and_symbols",
           "speed_dial",
           "ribbon",
           "shoe",
           "shopping_basket",
           "map",
           "ticket",
           "coins"
         ]},
      members: [{Asana.User, :compact}],
      minimum_access_level_for_customization: {:enum, ["admin", "editor"]},
      minimum_access_level_for_sharing: {:enum, ["admin", "editor"]},
      modified_at: {:string, "date-time"},
      name: :string,
      notes: :string,
      owner: {Asana.Project.Owner, :response},
      permalink_url: :string,
      privacy_setting: {:enum, ["public_to_workspace", "private_to_team", "private"]},
      project_brief: {Asana.Project.ProjectBrief, :response},
      public: :boolean,
      resource_type: :string,
      start_on: {:string, "date"},
      team: {Asana.Project.Team, :response},
      workspace: {Asana.Project.Workspace, :response}
    ]
  end
end
