defmodule Asana.Story do
  @moduledoc """
  Provides struct and types for a Story
  """
  use Asana.Encoder

  @type compact :: %__MODULE__{
          __info__: map,
          created_at: DateTime.t() | nil,
          created_by: Asana.User.compact() | nil,
          gid: String.t() | nil,
          resource_subtype: String.t() | nil,
          resource_type: String.t() | nil,
          text: String.t() | nil
        }

  @type response :: %__MODULE__{
          __info__: map,
          assignee: Asana.User.compact() | nil,
          created_at: DateTime.t() | nil,
          created_by: Asana.User.compact() | nil,
          custom_field: Asana.CustomField.compact() | nil,
          dependency: Asana.Task.compact() | nil,
          duplicate_of: Asana.Task.compact() | nil,
          duplicated_from: Asana.Task.compact() | nil,
          follower: Asana.User.compact() | nil,
          gid: String.t() | nil,
          hearted: boolean | nil,
          hearts: [Asana.Like.t()] | nil,
          html_text: String.t() | nil,
          is_editable: boolean | nil,
          is_edited: boolean | nil,
          is_pinned: boolean | nil,
          liked: boolean | nil,
          likes: [Asana.Like.t()] | nil,
          new_approval_status: String.t() | nil,
          new_date_value: Asana.Story.NewDateValue.response() | nil,
          new_dates: Asana.Story.ResponseDates.t() | nil,
          new_enum_value: Asana.EnumOption.t() | nil,
          new_multi_enum_values: [Asana.EnumOption.t()] | nil,
          new_name: String.t() | nil,
          new_number_value: integer | nil,
          new_people_value: [Asana.User.compact()] | nil,
          new_resource_subtype: String.t() | nil,
          new_section: Asana.Section.compact() | nil,
          new_text_value: String.t() | nil,
          num_hearts: integer | nil,
          num_likes: integer | nil,
          old_approval_status: String.t() | nil,
          old_date_value: Asana.Story.OldDateValue.response() | nil,
          old_dates: Asana.Story.ResponseDates.t() | nil,
          old_enum_value: Asana.EnumOption.t() | nil,
          old_multi_enum_values: [Asana.EnumOption.t()] | nil,
          old_name: String.t() | nil,
          old_number_value: integer | nil,
          old_people_value: [Asana.User.compact()] | nil,
          old_resource_subtype: String.t() | nil,
          old_section: Asana.Section.compact() | nil,
          old_text_value: String.t() | nil,
          previews: [Asana.Preview.t()] | nil,
          project: Asana.Project.compact() | nil,
          reaction_summary: [Asana.Reaction.SummaryItem.compact()] | nil,
          resource_subtype: String.t() | nil,
          resource_type: String.t() | nil,
          source: String.t() | nil,
          sticker_name: String.t() | nil,
          story: Asana.Story.compact() | nil,
          tag: Asana.Tag.compact() | nil,
          target: Asana.Story.Target.response() | nil,
          task: Asana.Task.compact() | nil,
          text: String.t() | nil,
          type: String.t() | nil
        }

  defstruct [
    :__info__,
    :assignee,
    :created_at,
    :created_by,
    :custom_field,
    :dependency,
    :duplicate_of,
    :duplicated_from,
    :follower,
    :gid,
    :hearted,
    :hearts,
    :html_text,
    :is_editable,
    :is_edited,
    :is_pinned,
    :liked,
    :likes,
    :new_approval_status,
    :new_date_value,
    :new_dates,
    :new_enum_value,
    :new_multi_enum_values,
    :new_name,
    :new_number_value,
    :new_people_value,
    :new_resource_subtype,
    :new_section,
    :new_text_value,
    :num_hearts,
    :num_likes,
    :old_approval_status,
    :old_date_value,
    :old_dates,
    :old_enum_value,
    :old_multi_enum_values,
    :old_name,
    :old_number_value,
    :old_people_value,
    :old_resource_subtype,
    :old_section,
    :old_text_value,
    :previews,
    :project,
    :reaction_summary,
    :resource_subtype,
    :resource_type,
    :source,
    :sticker_name,
    :story,
    :tag,
    :target,
    :task,
    :text,
    :type
  ]

  @doc false
  @spec __fields__(atom) :: keyword
  def __fields__(:compact) do
    [
      created_at: {:string, "date-time"},
      created_by: {Asana.User, :compact},
      gid: :string,
      resource_subtype: :string,
      resource_type: :string,
      text: :string
    ]
  end

  def __fields__(:response) do
    [
      assignee: {Asana.User, :compact},
      created_at: {:string, "date-time"},
      created_by: {Asana.User, :compact},
      custom_field: {Asana.CustomField, :compact},
      dependency: {Asana.Task, :compact},
      duplicate_of: {Asana.Task, :compact},
      duplicated_from: {Asana.Task, :compact},
      follower: {Asana.User, :compact},
      gid: :string,
      hearted: :boolean,
      hearts: [{Asana.Like, :t}],
      html_text: :string,
      is_editable: :boolean,
      is_edited: :boolean,
      is_pinned: :boolean,
      liked: :boolean,
      likes: [{Asana.Like, :t}],
      new_approval_status: :string,
      new_date_value: {Asana.Story.NewDateValue, :response},
      new_dates: {Asana.Story.ResponseDates, :t},
      new_enum_value: {Asana.EnumOption, :t},
      new_multi_enum_values: [{Asana.EnumOption, :t}],
      new_name: :string,
      new_number_value: :integer,
      new_people_value: [{Asana.User, :compact}],
      new_resource_subtype: :string,
      new_section: {Asana.Section, :compact},
      new_text_value: :string,
      num_hearts: :integer,
      num_likes: :integer,
      old_approval_status: :string,
      old_date_value: {Asana.Story.OldDateValue, :response},
      old_dates: {Asana.Story.ResponseDates, :t},
      old_enum_value: {Asana.EnumOption, :t},
      old_multi_enum_values: [{Asana.EnumOption, :t}],
      old_name: :string,
      old_number_value: :integer,
      old_people_value: [{Asana.User, :compact}],
      old_resource_subtype: :string,
      old_section: {Asana.Section, :compact},
      old_text_value: :string,
      previews: [{Asana.Preview, :t}],
      project: {Asana.Project, :compact},
      reaction_summary: [{Asana.Reaction.SummaryItem, :compact}],
      resource_subtype: :string,
      resource_type: :string,
      source: {:enum, ["web", "email", "mobile", "api", "unknown"]},
      sticker_name:
        {:enum,
         [
           "green_checkmark",
           "people_dancing",
           "dancing_unicorn",
           "heart",
           "party_popper",
           "people_waving_flags",
           "splashing_narwhal",
           "trophy",
           "yeti_riding_unicorn",
           "celebrating_people",
           "determined_climbers",
           "phoenix_spreading_love"
         ]},
      story: {Asana.Story, :compact},
      tag: {Asana.Tag, :compact},
      target: {Asana.Story.Target, :response},
      task: {Asana.Task, :compact},
      text: :string,
      type: {:enum, ["comment", "system"]}
    ]
  end
end
