defmodule Asana.Task do
  @moduledoc """
  Provides struct and types for a Task
  """
  use Asana.Encoder

  @type compact :: %__MODULE__{
          __info__: map,
          created_by: map | nil,
          gid: String.t() | nil,
          name: String.t() | nil,
          resource_subtype: String.t() | nil,
          resource_type: String.t() | nil
        }

  @type response :: %__MODULE__{
          __info__: map,
          actual_time_minutes: number | nil,
          approval_status: String.t() | nil,
          assigned_by: Asana.Task.AssignedBy.response() | nil,
          assignee: Asana.Task.Assignee.response() | nil,
          assignee_section: Asana.Task.AssigneeSection.response() | nil,
          assignee_status: String.t() | nil,
          completed: boolean | nil,
          completed_at: DateTime.t() | nil,
          completed_by: Asana.Task.CompletedBy.response() | nil,
          created_at: DateTime.t() | nil,
          created_by: Asana.Task.CreatedBy.response() | nil,
          custom_fields: [Asana.CustomField.response()] | nil,
          custom_type: Asana.Task.CustomType.response() | nil,
          custom_type_status_option: Asana.Task.CustomTypeStatusOption.response() | nil,
          dependencies: [Asana.AsanaResource.t()] | nil,
          dependents: [Asana.AsanaResource.t()] | nil,
          due_at: DateTime.t() | nil,
          due_on: Date.t() | nil,
          external: Asana.Task.External.response() | nil,
          followers: [Asana.User.compact()] | nil,
          gid: String.t() | nil,
          hearted: boolean | nil,
          hearts: [Asana.Like.t()] | nil,
          html_notes: String.t() | nil,
          is_rendered_as_separator: boolean | nil,
          liked: boolean | nil,
          likes: [Asana.Like.t()] | nil,
          memberships: [Asana.Task.Memberships.response()] | nil,
          modified_at: DateTime.t() | nil,
          name: String.t() | nil,
          notes: String.t() | nil,
          num_hearts: integer | nil,
          num_likes: integer | nil,
          num_subtasks: integer | nil,
          parent: Asana.Task.Parent.response() | nil,
          permalink_url: String.t() | nil,
          projects: [Asana.Project.compact()] | nil,
          resource_subtype: String.t() | nil,
          resource_type: String.t() | nil,
          start_at: DateTime.t() | nil,
          start_on: Date.t() | nil,
          tags: [Asana.Tag.compact()] | nil,
          workspace: Asana.Task.Workspace.response() | nil
        }

  defstruct [
    :__info__,
    :actual_time_minutes,
    :approval_status,
    :assigned_by,
    :assignee,
    :assignee_section,
    :assignee_status,
    :completed,
    :completed_at,
    :completed_by,
    :created_at,
    :created_by,
    :custom_fields,
    :custom_type,
    :custom_type_status_option,
    :dependencies,
    :dependents,
    :due_at,
    :due_on,
    :external,
    :followers,
    :gid,
    :hearted,
    :hearts,
    :html_notes,
    :is_rendered_as_separator,
    :liked,
    :likes,
    :memberships,
    :modified_at,
    :name,
    :notes,
    :num_hearts,
    :num_likes,
    :num_subtasks,
    :parent,
    :permalink_url,
    :projects,
    :resource_subtype,
    :resource_type,
    :start_at,
    :start_on,
    :tags,
    :workspace
  ]

  @doc false
  @spec __fields__(atom) :: keyword
  def __fields__(:compact) do
    [
      created_by: :map,
      gid: :string,
      name: :string,
      resource_subtype: {:enum, ["default_task", "milestone", "approval", "custom"]},
      resource_type: :string
    ]
  end

  def __fields__(:response) do
    [
      actual_time_minutes: :number,
      approval_status: {:enum, ["pending", "approved", "rejected", "changes_requested"]},
      assigned_by: {Asana.Task.AssignedBy, :response},
      assignee: {Asana.Task.Assignee, :response},
      assignee_section: {Asana.Task.AssigneeSection, :response},
      assignee_status: {:enum, ["today", "upcoming", "later", "new", "inbox"]},
      completed: :boolean,
      completed_at: {:string, "date-time"},
      completed_by: {Asana.Task.CompletedBy, :response},
      created_at: {:string, "date-time"},
      created_by: {Asana.Task.CreatedBy, :response},
      custom_fields: [{Asana.CustomField, :response}],
      custom_type: {Asana.Task.CustomType, :response},
      custom_type_status_option: {Asana.Task.CustomTypeStatusOption, :response},
      dependencies: [{Asana.AsanaResource, :t}],
      dependents: [{Asana.AsanaResource, :t}],
      due_at: {:string, "date-time"},
      due_on: {:string, "date"},
      external: {Asana.Task.External, :response},
      followers: [{Asana.User, :compact}],
      gid: :string,
      hearted: :boolean,
      hearts: [{Asana.Like, :t}],
      html_notes: :string,
      is_rendered_as_separator: :boolean,
      liked: :boolean,
      likes: [{Asana.Like, :t}],
      memberships: [{Asana.Task.Memberships, :response}],
      modified_at: {:string, "date-time"},
      name: :string,
      notes: :string,
      num_hearts: :integer,
      num_likes: :integer,
      num_subtasks: :integer,
      parent: {Asana.Task.Parent, :response},
      permalink_url: :string,
      projects: [{Asana.Project, :compact}],
      resource_subtype: {:enum, ["default_task", "milestone", "approval", "custom"]},
      resource_type: :string,
      start_at: {:string, "date-time"},
      start_on: {:string, "date"},
      tags: [{Asana.Tag, :compact}],
      workspace: {Asana.Task.Workspace, :response}
    ]
  end
end
